### ISSUE TITLE
treetop 1.4.12 specs fail with ruby 1.8

### ISSUE THREAD

**Issue by graaff** [nathansobo/treetop#32]
With ruby 1.8.7 (2012-10-12 patchlevel 371) [x86_64-linux] I get the following failures when trying to run the specs.

```
  1) a character class with a negated POSIX bracket expression matches a character outside the negated class
     Failure/Error: parse('a').should_not be_nil
     RegexpError:
       invalid regular expression; [:^space:] is not a character class: /\G[[:^space:]]/
     # ./lib/treetop/runtime/compiled_parser.rb:97:in `initialize'
     # ./lib/treetop/runtime/compiled_parser.rb:97:in `new'
     # ./lib/treetop/runtime/compiled_parser.rb:97:in `has_terminal?'
     # (eval):19:in `_nt_expression_under_test'
     # ./lib/treetop/runtime/compiled_parser.rb:18:in `send'
     # ./lib/treetop/runtime/compiled_parser.rb:18:in `parse'
     # ./spec/compiler/character_class_spec.rb:91

  2) a character class with a negated POSIX bracket expression doesn't match a character within the negated class
     Failure/Error: parse(' ').should be_nil
     RegexpError:
       invalid regular expression; [:^space:] is not a character class: /\G[[:^space:]]/
     # ./lib/treetop/runtime/compiled_parser.rb:97:in `initialize'
     # ./lib/treetop/runtime/compiled_parser.rb:97:in `new'
     # ./lib/treetop/runtime/compiled_parser.rb:97:in `has_terminal?'
     # (eval):19:in `_nt_expression_under_test'
     # ./lib/treetop/runtime/compiled_parser.rb:18:in `send'
     # ./lib/treetop/runtime/compiled_parser.rb:18:in `parse'
     # ./spec/compiler/character_class_spec.rb:94
```
